name = "ptvalert"
main = "cloudflare-worker.js"
compatibility_date = "2023-10-02"
usage_model = "bundled"
node_compat = true

# Triggers
[triggers]
crons = ["0 * * * *"] # Run hourly

# KV Namespaces bindings - Create these using wrangler CLI:
# wrangler kv:namespace create SUBSCRIPTIONS
# wrangler kv:namespace create MARKERS
# wrangler kv:namespace create ADMIN_USERS
# wrangler kv:namespace create BANNED_USERS

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual ID
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" # Replace with actual preview ID

[[kv_namespaces]]
binding = "MARKERS"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual ID
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" # Replace with actual preview ID

[[kv_namespaces]]
binding = "ADMIN_USERS"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual ID
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" # Replace with actual preview ID

[[kv_namespaces]]
binding = "BANNED_USERS"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual ID
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" # Replace with actual preview ID

# Environment variables
[vars]
VAPID_PUBLIC_KEY = "BIi0aWM8sQdsY8SIriYSG551h2HAezVghr6sudVRqEQeQu-6tILY6pbuytfDshoO7As3128FE791I0boTeNQD-8" # 用户提供的VAPID公钥
VAPID_PRIVATE_KEY = "x2d0l1bc7Nzt432do68nVaBARMNBKz5rX0HnVFYquLE" # 用户提供的VAPID私钥
VAPID_SUBJECT = "mailto:qingyangzhou85@gmail.com" # 用户提供的VAPID subject 