name = "ptvalert"
main = "worker.js"
compatibility_date = "2023-09-04"

# KV命名空间绑定
kv_namespaces = [
  { binding = "REPORTS", id = "813b223b2bd24ca4a50655c37d62e964", preview_id = "b5ddd27ffc2a4a479ebebdb97dd59dfd" },
  { binding = "SUBSCRIPTIONS", id = "3e834580823b431f93239c9092cc062d" },
  { binding = "MARKERS", id = "f0687e4580d64df484752257469e7742" },
  { binding = "ADMIN_USERS", id = "90d07da1d69a4c0cbdfeec29e0db07a1" },
  { binding = "BANNED_USERS", id = "e6ca3f9fb8264b078fc172106a4638b5" }
]

# 环境变量
[vars]
ENVIRONMENT = "production"
VAPID_PUBLIC_KEY = "BIi0aWM8sQdsY8SIriYSG551h2HAezVghr6sudVRqEQeQu-6tILY6pbuytfDshoO7As3128FE791I0boTeNQD-8"
VAPID_PRIVATE_KEY = "4GCZgKr2_lhj_LnpSLsv2X-9Kue4bq8GHPEZrKznnKw"

# 生产环境配置
[env.production]
route = { pattern = "ptvalert.qingyangzhou85.workers.dev", custom_domain = true }
workers_dev = true 