name = "push-notification-service"
main = "cloudflare-worker.js"
compatibility_date = "2023-12-01"

# 使用Wrangler CLI工具
# 用于开发和部署Cloudflare Workers

# KV命名空间用于存储订阅
[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "创建后填入此处" # 请通过wrangler命令创建并填入

# 设置环境变量
[vars]
# 以下环境变量将由wrangler secret命令添加
# VAPID_PUBLIC_KEY = "从界面设置"  
# VAPID_PRIVATE_KEY = "从界面设置"

# 配置触发器
[triggers]
# 每隔6小时检查一次新标记
crons = ["0 */6 * * *"] 